app:
  name: f-kernel

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.jkqj: DEBUG

canal:
  host: 127.0.0.1
  port: 11111
  destination: example
  username: canal
  password: 12345678
  subscribes:
    - jkqj_all.question
    - jkqj_all.user
    - jkqj_all.biz_user
    - jkqj_all.biz_user_company
    - jkqj_all.tag

mq:
  nats:
    pool-size: 10
    servers:
      - nats://localhost:4222
    connection-name: jkqj-mq
    username: jkqj_mq
    password: cswjggljrmpypwfccarzpjxG-urepqldkhecvnzxzmngotaqs-bkwdvjgipruectqcowoqb6nj
